import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    id 'fabric-loom' version '1.14-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    accessWidenerPath = file("src/main/resources/plotsquared-fabric.accessWidener")
    runs {
        client {
            runDir = "runClient"
            client()
        }
        server {
            runDir = "run"
            server()
        }
    }
}

repositories {
    maven { url = "https://cursemaven.com" }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }
    maven {
        name = "sonatype-oss-snapshots1"
        url = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
        mavenContent { snapshotsOnly() }
    }
    maven { url = 'https://maven.nucleoid.xyz/' }
    maven { url = "https://jitpack.io" }
    mavenCentral()
    flatDir {
        dirs 'DepLibs'
    }
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
}

def customAttribute = Attribute.of("String", String)

configurations {
    named("namedElements") {
        attributes {
            attribute(customAttribute, "test")
        }
    }
}
shadowJar {
    configurations = [project.configurations.shadow]
    dependsOn(":plotsquared-core:shadowJar")
    dependencies {
        exclude(dependency("org.checkerframework:"))
    }

/*
    relocate("net.kyori.option", "com.plotsquared.core.configuration.option")
    relocate("net.kyori.adventure", "com.plotsquared.core.configuration.adventure")
    relocate("net.kyori.examination", "com.plotsquared.core.configuration.examination")
    relocate("io.papermc.lib", "com.plotsquared.bukkit.paperlib")
    relocate("org.bstats", "com.plotsquared.metrics")
    relocate("org.enginehub", "com.plotsquared.squirrelid")
    relocate("org.khelekore.prtree", "com.plotsquared.prtree")
    relocate("com.google.inject", "com.plotsquared.google")
    relocate("org.aopalliance", "com.plotsquared.core.aopalliance")
    relocate("cloud.commandframework.services", "com.plotsquared.core.services")
    relocate("io.leangen.geantyref", "com.plotsquared.core.geantyref")
    relocate("com.intellectualsites.arkitektonika", "com.plotsquared.core.arkitektonika")
    relocate("com.intellectualsites.http", "com.plotsquared.core.http")
    relocate("com.intellectualsites.paster", "com.plotsquared.core.paster")
    relocate("org.incendo.serverlib", "com.plotsquared.bukkit.serverlib")
    relocate("org.jetbrains", "com.plotsquared.core.annotations")
    relocate("org.intellij.lang", "com.plotsquared.core.intellij.annotations")
    relocate("javax.annotation", "com.plotsquared.core.annotation")
    relocate("com.github.spotbugs", "com.plotsquared.core.spotbugs")
    relocate("javax.inject", "com.plotsquared.core.annotation.inject")
    relocate("net.jcip", "com.plotsquared.core.annotations.jcip")
    relocate("edu.umd.cs.findbugs", "com.plotsquared.core.annotations.findbugs")
    relocate("com.intellectualsites.annotations", "com.plotsquared.core.annotations.informative")
*/
    exclude("META-INF")
    minimize()


    mergeServiceFiles()
}

remapJar{
    var shadow = tasks.named("shadowJar", ShadowJar)
    dependsOn(shadow)
    mustRunAfter(shadow)
    inputFile.set(shadowJar.getArchiveFile().get())
    addNestedDependencies.set(true)
}

assemble {
    dependsOn(remapJar)
}


dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    api(projects.plotsquaredCore)
    shadow(projects.plotsquaredCore)
    modImplementation (include("net.kyori:adventure-platform-fabric:5.14.2"))
    //shadow("net.kyori:adventure-platform-fabric:5.8.0")
    modImplementation (include("net.kyori:adventure-api:4.17.0"))
   // shadow("net.kyori:adventure-api:4.17.0")
    modImplementation (include("net.kyori:adventure-text-minimessage:4.17.0"))
    //shadow("net.kyori:adventure-text-minimessage:4.17.0")
    modImplementation (include("net.kyori:adventure-text-serializer-legacy:4.17.0"))
    //shadow("net.kyori:adventure-text-serializer-legacy:4.17.0")
    modImplementation (include("dev.notmyfault.serverlib:ServerLib:2.3.7"))
    //modImplementation(libs.worldeditCore)
   // modImplementation("curse.maven:worldedit-225608:4586218")
    modCompileOnly("name:FastAsyncWorldEdit-Fabric-2.13.2-SNAPSHOT")
    modImplementation("xyz.nucleoid:stimuli:0.4.12+1.21")
    //shadow("xyz.nucleoid:stimuli:0.4.8+1.20.1")
    modCompileOnlyApi("net.luckperms:api:5.4")
    modImplementation("io.github.miniplaceholders:miniplaceholders-api:2.3.0")
    //modCompileOnly("name:Multiworld-Fabric-1.21") //multiworld
    modCompileOnlyApi("name:worldmanager-1.4.0+1.21.1")
    modCompileOnlyApi("xyz.nucleoid:fantasy:0.6.4+1.21")
    modCompileOnlyApi("maven.modrinth:rCEje2Lt:bTyKGlcm")
    modCompileOnlyApi("maven.modrinth:N6n5dqoA:6BFd0w5s")
    implementation(include(libs.squirrelid.get())) {transitive = false}
    implementation(include(libs.arkitektonika.get()))
    implementation(include(libs.paster.get()))
    implementation(include(libs.informativeAnnotations.get()))
    modImplementation(include("org.apache.commons:commons-compress:1.21"))
    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.4.0-beta.2")))
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

def targetJavaVersion = 21
tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    //withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}
